# Generated by Django 4.2.4 on 2023-08-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutividadeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('secao', models.CharField(max_length=150)),
                ('percentual', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProdutividadeAdt',
            fields=[
                ('produtividadebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.produtividadebase')),
                ('complexidade', models.CharField(max_length=150)),
            ],
            bases=('website.produtividadebase',),
        ),
        migrations.CreateModel(
            name='ProdutividadeSedoc',
            fields=[
                ('produtividadebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.produtividadebase')),
                ('complexidade', models.CharField(max_length=150)),
            ],
            bases=('website.produtividadebase',),
        ),
    ]
